import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';

import AntdProvider from 'providers/antd-provider';

import Container from 'components/core-ui/container/container';
import Footer from 'components/layout/footer';
import Header from 'components/layout/header';

import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        // media: "(prefers-color-scheme: dark)",
        url: '/favicon.ico',
        href: '/favicon.ico',
      },
      // {
      //   media: "(prefers-color-scheme: light)",
      //   url: "/images/favicon-dark.png",
      //   href: "/images/favicon-dark.png",
      // },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        <AntdProvider>
          <Container>
            <Header />
            {children}
            <Footer />
          </Container>
        </AntdProvider>
      </body>
    </html>
  );
}
